### ISSUE TITLE
Caraya behavor change 1.0 to 1.1 - how to handle?

### ISSUE THREAD

**Issue by AndrewHeim** [LabVIEW-Open-Source/Caraya-CLI-extension#2]
Thank you for the fast turnaround!  (conversation continuing from #1)

Indeed, Caraya does have a behavioral change.  Batch tests returned an error in 1.0 if any test failed - but does not in v1.1. 

If we wanted to patch over that change here, one fix is to pin to Caraya to v1.0.  But that doesn't really have legs long term - Caraya 1.1 has great stuff!

One approach is to ask the Test Runner class if any tests failed, rather than relying on the error returned from Caraya.  But when we interrogated it, it wasn't returning meaningful information in the Test Report object - at least in our tests from how we understand it.
 It looks like it could be getting emptied upstream, before it gets passed out.

![image](https://user-images.githubusercontent.com/10777768/107297417-89ee4380-6a30-11eb-9292-697b5b8e1267.png)

This returns zero elements in the Test Results array.

Do you think this is worth working around here?  I suppose we need to work with Caraya to see how intentional this change was there first, don't we?

**Comment by francois-normandin** [comment]
I would definitely prefer we find the issue and fix it to make use of 1.1 features!

Would you be able to create a small example which reproduces the issue?

There is a new Test Result output from the Test Suite. Perhaps this is where the behavior changed from the perspective of the Batch Test. If so, it might be a Caraya issue, and not a Caraya CLI Extension issue.

Here is the full list of changes between Caraya 1.0 and 1.1 (it is probably one of these):

> New Features:
> [Feature: 94] Added a Pre-Build PassFail verification step for package building
> **[Feature: 95] Test Suite now returns a "Test Result" object when it completes.**
> 
> Fixes:
> [Fix: 98] Fixed the error on re-running tests from the Test Manager when called from "Run Tests in Active Project"
> [Fix: 100] Test Event storage now uses Test and Assert IDs to update verbose explanations in reports
> **[Fix: 101] Broken VIs are now handled properly in the Batch Running all Tests in Active Project**
> [Fix: 102] Conditionally disable the "UI: Update Count" frame content on RT targets
> [Fix: 103] OpenG dependencies are now included in the package (and namespaced)
> [Fix: 104] Asserts in SubVIs not appearing as expected in JUnit reports
> [Fix: 109] The Test Name is used instead of VI File Name
> [Fix: 110] Test Event storage now uses Test and Assert IDs to update verbose explanations in reports

**Comment by AndrewHeim** [comment]
It looks like the guts of what "Run Batch Tests" calls got rewritten between versions.  Not just a minor change, but a complete refactor.  I suspect that's what caused the problem.

I'm wanting to file a bug, but haven't because I don't have the details.  Last time I started looking at them, I got confused as to which VIs were in which version of Caraya and what came with the CLI tools.  Run Batch Tests.vi comes with Caraya, right?

I'm willing to try to fix it, but might need help getting pointed in the right direction.

**Comment by francois-normandin** [comment]
@AndrewHeim I'd much appreciate any help you can give. My hands are full with some other projects and this one falls a bit below my radar, to be quite honest ;-)

**Comment by AndrewHeim** [comment]
I did it!  Submitted upstream here: https://github.com/JKISoftware/Caraya/issues/130

I was confused at things calling Caraya CLI.vi instead of Run Tests Programmatically.vi, but no matter which way you do it, it all ends up in Run Tests Programmatically.vi

**Comment by francois-normandin** [comment]
@AndrewHeim I fixed the problem and will have an updated package in a few hours. I built it and tested it, but I had to leave before I missed my bus... Long story short, I've decided it was easier to use the new "Run tests" method that was introduced in Caraya 1.1, which is definitely a node I had in mind when I created the CLI extension in the first place. The node is probably the most used node nowadays in Caraya because it is called from the QD plugin and a bunch of tools menu add-ons. The batch runner in silent mode was an overload too many...

**Comment by francois-normandin** [comment]
Package released here:
https://github.com/LabVIEW-Open-Source/Caraya-CLI-extension/releases/tag/1.1.0

I'll see to add this to VIPM

Documentation screenshot:
![image](https://user-images.githubusercontent.com/11728548/110629944-c5387b00-8172-11eb-8382-668ca3713fc4.png)

**Comment by AndrewHeim** [comment]
Thank you!
