### ISSUE TITLE
Change CLI tool installation path

### ISSUE THREAD

**Issue by OlivierJourdan** [LabVIEW-Open-Source/Caraya-CLI-extension#3]
To make the call to the CLI tool easier (and if nothing is against that) install CarayaCLIExecutionEngine.vi into \vi.lib\G CLI Tools folder. The command line could be change to 

`g-cli --lv-ver <LABVIEW_VERSION> CarayaCLIExecutionEngine -- -s "<SOURCE_TEST_FOLDER>" -x "<OUTPUT_FILEPATH>"`

See G-CLI documentation here --> https://github.com/JamesMc86/G-CLI/wiki/Creating-Tools-To-Work-With-G-CLI#setup-installer

NOTE: I would also rename the VI to RunCaraya.vi or something that sounds more a command name.

**Comment by francois-normandin** [comment]
Good ideas. I'll add your suggestion in the proposed folder and keep the existing one for backward compatibility.
And renaming the method makes sense too. A wrapper should do it.

**Comment by francois-normandin** [comment]
I'll need to do a few tests.
This suggestion will work when calling from the IDE... I'm wondering if there are any use cases where we would like to call the CLI from an Executable, and if so, what are the impacts?

I'm sure both cases can be handled elegantly, probably by handling both relative and absolute paths, which the G-CLI does gracefully in the IDE.

**Comment by stagg54** [comment]
I second this idea. I came here to suggest the same thing.

**Comment by francois-normandin** [comment]
@stagg54 I should have time this weekend to work on that. Do you have a pull request? If not, I think that's a quick addition anyhow.

**Comment by stagg54** [comment]
I also like the idea of leaving the existing code as is and just adding a wrapper. Seems very straightforward and maintains backward compatibility.

**Comment by stagg54** [comment]
What version of LabVIEW is this using?

**Comment by stagg54** [comment]
Also as to your question about paths, I think the way it works with G-CLI and James Mac can confirm, if you use a relative path, G-CLI first looks relative to the working directory and if it can't find the VI there, then it looks in the <.vilib>/G-CLI directory.

**Comment by stagg54** [comment]
If I happen to have a VM setup already with the correct version of LV, I'm happy to do the work and submit a pull request.

Also happy to test it, once its ready.

**Comment by stagg54** [comment]
Here is confirmation on the search pattern
![image](https://github.com/LabVIEW-Open-Source/Caraya-CLI-extension/assets/20363351/da848125-cdc9-4756-a5c3-5cf5df33451a)

**Comment by francois-normandin** [comment]
LV2013, if your want to give it a shot

**Comment by stagg54** [comment]
Unfortunately I don't happen to have an LV 2013 VM sitting around. I'm going to assume you do, so I'll let you handle that. Happy to help test though.

**Comment by stagg54** [comment]
Note when you create the wrapper you'll probably need to change the name to something else. I would suggest either simply Caraya or CarayaCLI.

**Comment by stagg54** [comment]
or Olivier's suggestion of RunCaraya also works... It doesn't really matter much to me what it ends up being.

**Comment by francois-normandin** [comment]
I see errors with G-CLI 2.3 and 2.4. Might need to update to 3.x, but LV 2013 is no longer supported.

https://forums.ni.com/t5/LabVIEW/Unhandled-exception-running-g-cli/td-p/4270238
![image](https://github.com/LabVIEW-Open-Source/Caraya-CLI-extension/assets/11728548/e750d9f7-491b-4010-9924-4cc0c2061ea8)

**Comment by francois-normandin** [comment]
I`ll have to rev this code up to version 2.0 and support 2017+ or 2019+

@stagg54 @OlivierJourdan 
I believe that upgrading past 2013, I would prefer to move to LV2020 since it is the Community Edition. Any objections?

**Comment by OlivierJourdan** [comment]
No objection for me 😄

**Comment by stagg54** [comment]
no objection from me. 2020 is what I have been standardizing on. It will make it much easier for me to contribute.

For older legacy code, people can always use the old version of Caraya and it's still fully functional. I mean people are using it right now. These changes just make it a little easier to use with CI.

**Comment by francois-normandin** [comment]
Version 2.x will support calling "RunCaraya" or "Caraya" (wrappers installed in G-CLI Tools folder)

![image](https://github.com/LabVIEW-Open-Source/Caraya-CLI-extension/assets/11728548/fff6a9f8-98f9-4b92-82ce-e3ba00dfe707)
