### ISSUE TITLE
Do not call "Quit LabVIEW" when action is finished

### ISSUE THREAD

**Issue by OlivierJourdan** [LabVIEW-Open-Source/Caraya-CLI-extension#4]
The call to Quit LabVIEW function is making the next job of my CI fail.

I guess that LabVIEW exits after the next call to LabVIEW with G-CLI or LabVIEW CLI is made.

In a general way, I'd think that it's the responsibility of the CI process to choose when LabVIEW have to be stoped.

**Comment by francois-normandin** [comment]
Agreed. @OlivierJourdan 

Thanks for the report. This was thrown together quickly and I must admit that I've never used it outside of quick demos ;-)

**Comment by francois-normandin** [comment]
I will be adding a "-q"  argument to quit LabVIEW automatically after the call. This feature will default to FALSE in the next version.

I consider this a bug, not a feature. You are 100% correct that this CLI caller should never have taken the responsibility to exit LabVIEW unless specified through an argument. Anyone currently relying on this library version <= 1.1 to close LabVIEW will have to add -q to their CI call or handle exiting LabVIEW on their own.

**Comment by OlivierJourdan** [comment]
I like the way you want to fix this "bug" 👍

**Comment by francois-normandin** [comment]
-q will be required to Exit LabVIEW when done.

![image](https://github.com/LabVIEW-Open-Source/Caraya-CLI-extension/assets/11728548/fff6a9f8-98f9-4b92-82ce-e3ba00dfe707)
